name: Server Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci --workspaces=false
      - run: npm --workspace server ci || npm --workspace server install
      - run: npm --workspace server run start --if-present


